name: run-full-test

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK (java18)
        uses: actions/setup-java@v3
        with:
          java-version: 18
          distribution: corretto

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Run tests
        env:
          POM_DIRECTORY: ${{ inputs.pomDirectory }}
        run: mvn -f "./java-utils/pom.xml" test